### PR TITLE
Make dict as JSON

### PR DESCRIPTION
**Pull request by bloodbare**

### CODE REVIEW

**Review by ebrehault — APPROVED** [review]

**Review by ebrehault — APPROVED** [review]
@bloodbare if you're ok with it, I will remove the `parse` method and just use the `ask` method to support both regular answer and JSON answer. I think it will make more sense for the users.

**Comment by bloodbare** [comment]
I would be expecting is that the parse is returning an Object validated. The `answer` attribute is a string.

**Comment by ebrehault** [comment]
> I would be expecting is that the parse is returning an Object validated. The `answer` attribute is a string.

ok, well I guess it can be manage with a `Union`, but ok we can also have 2 different methods.
In that case, I just recommend we rename `parse` into something more explicit (like `ask_json`), because `parse` is very confusing.

**Comment by bloodbare** [comment]
> > I would be expecting is that the parse is returning an Object validated. The `answer` attribute is a string.
> 
> ok, well I guess it can be manage with a `Union`, but ok we can also have 2 different methods. In that case, I just recommend we rename `parse` into something more explicit (like `ask_json`), because `parse` is very confusing.

Yups lets change it !

**Pull request merged**
